# .gitlab-ci.yml
stages:
  - build
  - deploy

# Build the project
build:
  stage: build
  image: node:18 # Node.js version image
  script:
    - npm ci # Install dependencies cleanly
    - npm run build -- --emptyOutDir # Build the Vite React app
  artifacts:
    paths:
      - dist # Store the build artifacts
    expire_in: 1 week # Retain build files for a week

# Deploy the build artifacts to the remote Linux machine
deploy:
  stage: deploy
  image: alpine:latest
  before_script:
    - apk add --no-cache openssh
    - mkdir -p ~/.ssh
    - echo "$SSH_KNOWN_HOSTS" > ~/.ssh/known_hosts
    - eval $(ssh-agent -s)  # Start SSH agent
    - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -  # Add private key for remote server
  script:
    - ssh -o StrictHostKeyChecking=no $SSH_USER@$SSH_HOST "cd /home/dev/client && git pull origin staging && npm install && npm run build -- --emptyOutDir"
    - scp -r dist/* $SSH_USER@$SSH_HOST:/var/www/client
  only:
    - staging

